# Download Java
ARG JAVA_VERSION="18-jdk"
FROM openjdk:${JAVA_VERSION}

LABEL versioin="1.0.0"

ENV PROJECT_NAME="pagination-api"
ENV MYSQL_HOST=mysqlDb
ENV MYSQL_PORT=3306
ENV MYSQL_DATABASE=paginationDb
ENV MYSQL_USERNAME=root
ENV MYSQL_PASSWORD=root

#ARG APP_HOME="/opt/deployment/"

# Copy the jar from local to image
#RUN mkdir ${APP_HOME}
COPY target/pagiantion.jar /pagiantion.jar

#WORKDIR ${APP_HOME}

EXPOSE 8080

# Run application with java -jar
ENTRYPOINT ["java", "-jar", "pagiantion.jar"]